services:
  - type: web
    name: nahana-brief-webapp
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: NEXT_PUBLIC_CLERK_SIGN_IN_URL
        value: /sign-in
      - key: NEXT_PUBLIC_CLERK_SIGN_UP_URL
        value: /sign-up
      - key: NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL
        value: /
      - key: NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL
        value: /
      - key: N8N_API_KEY
        sync: false
      - key: N8N_WEBHOOK_URL
        value: https://n8n-service-pafl.onrender.com/webhook/brief-processor 